//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odec.Server.Model.Conversation.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201604252213396_ConversationInitial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201604252213396_ConversationInitial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("odec.CP.Server.Model.Conversation.Migrations.201604252213396_ConversationInitial", typeof(_201604252213396_ConversationInitial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO0da2/cuPF7gf6HxX5qC5/XdnDFNVjfIdkkPbd5GF7n0G+BrKXXwumxJ2lzNor+sn7oT+pfKCnqwceQIkVJq70aAZIsH0POcGZIzZAz//33f5Y/PEbh7CtKsyCJL+fnp2fzGYr9ZBPE28v5Pr//5rv5D9///nfLt5vocfZT1e4FaYd7xtnl/CHPdy8Xi8x/QJGXnUaBnyZZcp+f+km08DbJ4uLs7C+L8/MFwiDmGNZstrzZx3kQoeIH/rlKYh/t8r0Xfkg2KMzKclyzLqDOPnoRynaejy7nuIF/ukYpnvNp0foU9yYIeDmeGvmRo8c8m89ehYGHp7dG4f185sVxkhctXn7O0DpPk3i73uECL7x92iHc7t4LM1Qi9bJpborf2QXBb9F0rED5+yxPIkuA5y9Kgi3E7p3IPq8Jikn6FpM+fyJYF2S9nLP0+4CyzNtiOojjvlyFKeljsgAitJOZvs9JzVhnp+TP+cXJbLUP832KLmO0z1Mv [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
